### ISSUE TITLE
sintax error using django 1.8 and python2.7.

### ISSUE THREAD

**Issue by marcathian** [krisfields/django-baker#15]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/contrib/admin/**init**.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/marc/geonode-dev/.venvs/djangocaketut/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/marc/djangocaketut/djangocaketut/bread/admin.py", line 2
    from .models import 
                       ^
SyntaxError: invalid syntax

**Comment by krisfields** [comment]
Let me know if this is still an issue.  I just pushed a big update - I think any issues should be fixed now so closing for now.
